### Local Tests ###

# Get all contacts
GET http://localhost:3000/contacts

# Get contact by ID 
GET http://localhost:3000/contacts/68c8417520247ffb70089449

# Test root endpoint
GET http://localhost:3000/


### Production Tests ###

# Root endpoint
#  Access API Guide
GET https://cse341-project1-x6z9.onrender.com/ 

# Get all contacts
GET https://cse341-project1-x6z9.onrender.com/contacts 

# Get contact by ID 
GET https://cse341-project1.onrender.com/contacts/68c8417520247ffb70089449



